name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck jq mpv curl fzf chafa yt-dlp

    - name: Install xh
      run: |
        curl -sL https://github.com/ducaale/xh/releases/latest/download/xh-x86_64-unknown-linux-gnu.tar.gz | tar xz
        sudo mv xh-x86_64-unknown-linux-gnu/xh /usr/local/bin/
    - name: Lint with ShellCheck
      run: shellcheck ytsurf.sh

    - name: Run Sanity Checks
      run: |
        # Test that the script runs with the --history flag (non-interactive)
        ./ytsurf.sh --history

        # Test that the script exits with an error on invalid input
        # We expect this to fail, so we invert the exit code with !
        ! ./ytsurf.sh --limit "not-a-number"
